create_task:
  description: Create a new task in Vikunja
  fields:
    title:
      description: Title of the task
      example: "Buy milk"
      required: true
    description:
      description: Description of the task
      example: "From the grocery store"
      required: false
    project_id:
      description: Project ID to add the task to
      example: 1
      required: false
      default: 1
    due_date:
      description: Due date for the task in ISO format (YYYY-MM-DDTHH:MM:SS)
      example: "2023-12-31T18:00:00"
      required: false
